language: php

jobs:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.4
      env: DEPLOY=true
    - php: nightly
  allow_failures:
    - php: nightly

install:
  - pecl install ast
  - phpenv config-rm xdebug.ini
  - composer validate --strict
  - composer install --ignore-platform-reqs --no-interaction

script:
  - vendor/bin/phan
  - vendor/bin/phpunit --testdox tests

before_deploy:
  - php ./scripts/build-docs.php
  - docker run --rm -it -v ${PWD}:/docs squidfunk/mkdocs-material build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site
  on:
    branch: master
    condition: $DEPLOY = true
