name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Run tests and deploy
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      matrix:
        php-version: ['7.1', '7.2', '7.3', '7.4']
        include:
          - php-version: '8.0'
            deploy: ${{ github.ref == 'refs/heads/master' }}
          - php-version: '8.1'
            experimental: true
    steps:
      # Download code from repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ast

      # Setup Composer
      - name: Setup Composer
        run: composer validate --strict && composer install --ignore-platform-reqs

      # Run static analyzer
      - name: Run static analyzer
        if: ${{ success() && matrix.php-version != '7.1' }}
        run: vendor/bin/phan

      # Run tests
      - name: Run tests
        run: vendor/bin/simple-phpunit --testdox

      # Build documentation
      - name: Build documentation
        if: ${{ success() && matrix.deploy || false }}
        run: |
          php ./scripts/build-docs.php
          docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build

       # Deploy documentation
      - name: Deploy documentation
        if: ${{ success() && matrix.deploy || false }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
          CLEAN: true # Automatically remove deleted files from the deploy branch
